export const GET_CURRENCY_NAMES = 'GET_CURRENCY_NAMES'
export const GET_EXCHANGE_RATES = 'GET_EXCHANGE_RATES'
export const GET_COUNTRY_TO_CURRENCY = 'GET_COUNTRY_TO_CURRENCY'
export const SET_OPTION = 'SET_OPTION'